# -*- coding: utf-8 -*-
"""FoodVision1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14clHX5IO7Rz-13NRAGG19uuPYVK2YAzD

## Importing libararies
"""

import torch
from torch import nn
import torchvision
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
from torchvision import datasets
from torchvision import transforms
from pathlib import Path
import random
from google.colab import drive
import numpy as np
drive.mount('/content/drive')

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

torch.__version__

!pip install gradio tensorboard

"""## Get Data"""

from torchvision import transforms

data_path = Path('Data')
image_path = data_path / 'Food'
if image_path.is_dir():
   print(f'{image_path} directory already exists... ')
else:
  print(f'{image_path} does not exist, creating one...')
  image_path.mkdir(parents =True, exist_ok= True)

# Define transforms here, before dataset initialization
train_transform  = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor()
])

test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])

train_data = torchvision.datasets.Food101(root =image_path,
                                   split= 'train',
                                   download = True,
                                   transform=train_transform # Pass transform directly
                                   )

test_data = torchvision.datasets.Food101(root = image_path,
                                         split = 'test',
                                         download= False,
                                         transform=test_transform # Pass transform directly
                                         )

print(f"Training images: {len(train_data)}")
print(f"Test images: {len(test_data)}")
print(f"Classes: {train_data.classes[:10]}")  # أول 10 أصناف

"""### 2.1 Transforming data with torchvision.transforms

"""

train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

train_data = torchvision.datasets.Food101(
    root=image_path, split='train', download=True, transform=train_transform
)
test_data = torchvision.datasets.Food101(
    root=image_path, split='test', download=False, transform=test_transform
)

print(f"Training images: {len(train_data)}")
print(f"Test images: {len(test_data)}")
print(f"Number of classes: {len(train_data.classes)}")
print(f"First 10 classes: {train_data.classes[:10]}")

"""### 2.2 Visualizing our data"""

original_data = torchvision.datasets.Food101(root=image_path, split='train', download=False)

img, label = original_data[0]  #
transformed_img = train_transform(img)

def plot_transformed_images(dataset, transform, n=3, seed=None):
    random.seed(seed)
    random_indices = random.sample(range(len(dataset)), k=n)

    for idx in random_indices:
        img, label = dataset[idx]
        print(type(img), img.shape if hasattr(img, 'shape') else img.size)
        fig, ax = plt.subplots(1, 2)

        ax[0].imshow(img)
        ax[0].set_title(f"Original\nSize: {img.size}")
        ax[0].set_axis_off()

        transformed = transform(img).permute(1, 2, 0)
        ax[1].imshow(transformed)
        ax[1].set_title(f"Transformed\nShape: {transformed.shape}")
        ax[1].set_axis_off()

        fig.suptitle(f"Class: {dataset.classes[label]}")
        plt.show()

plot_transformed_images(dataset=original_data, transform=train_transform, n=10)

"""### 2.3 Creating DataLoaders"""

from torch.utils.data import Subset
train_dataloader = DataLoader(Subset(train_data, torch.randperm(len(train_data))[:50000]),
                          batch_size=64,
                          shuffle=True,
                           num_workers=2)
test_dataloader  = DataLoader(Subset(test_data, torch.randperm(len(test_data))[:15000]),
                         batch_size=64,
                         shuffle=False,
                         num_workers=2)

len(train_dataloader), len(test_dataloader)

imgs, labels = next(iter(train_dataloader))
print(imgs.shape)

"""## #  Train and Test Function"""

loss_fn = nn.CrossEntropyLoss()
results = {}

def train_and_test(model, name, epochs=5, lr=0.001):
    model.to(device)
    optimizer = torch.optim.Adam(
        filter(lambda p: p.requires_grad, model.parameters()), lr=lr
    )

    # Training
    for epoch in range(epochs):
        model.train()
        running_loss = 0
        for imgs, labels in train_dataloader:
            imgs, labels = imgs.to(device), labels.to(device)
            optimizer.zero_grad()
            loss = loss_fn(model(imgs), labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
        print(f"{name} | Epoch {epoch+1}/{epochs} | Loss: {running_loss/len(train_dataloader):.4f}")

    # Testing
    model.eval()
    correct, total, test_loss = 0, 0, 0
    with torch.no_grad():
        for imgs, labels in test_dataloader:
            imgs, labels = imgs.to(device), labels.to(device)
            preds = model(imgs)
            test_loss += loss_fn(preds, labels).item()
            correct += (preds.argmax(1) == labels).sum().item()
            total += len(labels)

    acc = correct / total
    avg_loss = test_loss / len(test_dataloader)
    results[name] = {"accuracy": acc, "loss": avg_loss}
    print(f" {name} | Accuracy: {acc:.2%} | Loss: {avg_loss:.4f}\n")

    # Save and clean up
    save_path = f"/content/drive/MyDrive/FoodVision/{name}.pth"
    torch.save(model.state_dict(), save_path)
    print(f" Saved to {save_path}")
    del model
    torch.cuda.empty_cache()

"""## Model 1: EfficientNet-B0"""

m = torchvision.models.efficientnet_b0(weights=torchvision.models.EfficientNet_B0_Weights.DEFAULT)

# جمّدي الكل
for p in m.parameters():
    p.requires_grad = False

for p in m.features[-2:].parameters():
    p.requires_grad = True

m.classifier = nn.Sequential(nn.Dropout(0.2), nn.Linear(1280, 101))

train_and_test(m, "B0-FineTuned", epochs=5, lr=0.0001)

"""## Model 2: EfficientNet-B2"""

m = torchvision.models.efficientnet_b2(weights=torchvision.models.EfficientNet_B2_Weights.DEFAULT)
for p in m.parameters():
    p.requires_grad = False
m.classifier = nn.Sequential(nn.Dropout(0.3), nn.Linear(1408, 101))
train_and_test(m, "EfficientNet-B2_smallerDataSet.pth")

"""## Model 3: ResNet50"""

m = torchvision.models.resnet50(weights=torchvision.models.ResNet50_Weights.DEFAULT)
for p in m.parameters():
    p.requires_grad = False
for p in m.layer4.parameters():
    p.requires_grad = True
m.fc = nn.Linear(2048, 101)
train_and_test(m, "ResNet50-FineTuned-Full", epochs=5, lr=0.0001)

"""##   Results Comparison"""

print("\n" + "="*50)
print("Results Comparison")
print("="*50)
for name, res in results.items():
    print(f"{name:20s} | Accuracy: {res['accuracy']:.2%} | Loss: {res['loss']:.4f}")

print("\n" + "="*50)
print("Results Comparison")
print("="*50)
for name, res in results.items():
    print(f"{name:20s} | Accuracy: {res['accuracy']:.2%} | Loss: {res['loss']:.4f}")

"""##  Loading Saved Models"""

model_b0 = torchvision.models.efficientnet_b0(weights=None)
 model_b0.classifier = nn.Sequential(nn.Dropout(0.2), nn.Linear(1280, 101))
 model_b0.load_state_dict(torch.load('/content/drive/MyDrive/FoodVision/B0-FineTuned.pth'))
 model_b0.to(device)
 model_b0.eval()

 model_b2 = torchvision.models.efficientnet_b2(weights=None)
 model_b2.classifier = nn.Sequential(nn.Dropout(0.3), nn.Linear(1408, 101))
 model_b2.load_state_dict(torch.load('/content/drive/MyDrive/FoodVision/EfficientNet-B2_smallerDataSet.pth.pth'))
 model_b2.to(device)
 model_b2.eval()

 model_resnet = torchvision.models.resnet50(weights=None)
 model_resnet.fc = nn.Linear(2048, 101)
 model_resnet.load_state_dict(torch.load('/content/drive/MyDrive/FoodVision/ResNet50-FineTuned-Full.pth'))
 model_resnet.to(device)
 model_resnet.eval()

"""## Deep Error Analysis"""

data_path = Path('Data')
image_path = data_path / 'Food'
class_names = test_data.classes
print(f'Test data: {len(test_data)} images, {len(class_names)} classes')

class_names

"""### Getting predictions

#### Creating a function for prediction allocation

This function is used to:

1. Run the model on the data
2. Collect the predictions
3. Collect the true labels
4. Collect the probability scores for each class
5. Return everything ready for analysis or evaluation
"""

import numpy as np
def get_predictions(model, dataloader):

  """
                  This function is going to run the model on the data and
                  collect the predictions with the true labels and
                   the probability scores for each class then
                  return everything """

  all_preds, all_labels, all_probs = [], [], []
  model.eval()
  with torch.no_grad():
        for images, labels in dataloader:
            images = images.to(device)

            # Forward pass
            outputs = model(images)

            # Convert outputs to probabilities
            probs = torch.softmax(outputs, dim=1)

            ## Get predicted labels
            all_preds.extend(outputs.argmax(1).cpu().numpy())

            # Save true labels
            all_labels.extend(labels.numpy())

            # Save probabilities
            all_probs.extend(probs.cpu().numpy())

  return np.array(all_preds), np.array(all_labels), np.array(all_probs)

"""#### Calling the function on our models"""

print('Getting predictions...')
preds_b0, labels_all, probs_b0 = get_predictions(model_b0, test_dataloader)
print(f'B0 Accuracy: {(preds_b0 == labels_all).mean():.2%}')
preds_b2, _, probs_b2 = get_predictions(model_b2, test_dataloader)
print(f'B2 Accuracy: {(preds_b2 == labels_all).mean():.2%}')
preds_resnet, _, probs_resnet = get_predictions(model_resnet, test_dataloader)
print(f'ResNet50 Accuracy: {(preds_resnet == labels_all).mean():.2%}')

"""###  Model Comparison Table"""

import time, os

sizes = {
    'EfficientNet-B0': os.path.getsize('/content/drive/MyDrive/FoodVision/EfficientNet-B0_Small-dataset.pth') / 1e6,
    'EfficientNet-B2': os.path.getsize('/content/drive/MyDrive/FoodVision/EfficientNet-B2_smallerDataSet.pth.pth') / 1e6,
    'ResNet50': os.path.getsize('/content/drive/MyDrive/FoodVision/ResNet50-FineTuned-Full.pth') / 1e6,
}

def measure_speed(model, loader, n=10):
    model.eval()
    start = time.time()
    with torch.no_grad():
        for i, (imgs, _) in enumerate(loader):
            if i >= n: break
            _ = model(imgs.to(device))
    return (time.time() - start) / n

s_b0 = measure_speed(model_b0, test_dataloader)
s_b2 = measure_speed(model_b2, test_dataloader)
s_resnet = measure_speed(model_resnet, test_dataloader)

print(f"{'Model':<20} {'Accuracy':<12} {'Speed (s/batch)':<18} {'Size (MB)'}")
print('=' * 62)
print(f"{'EfficientNet-B0':<20} {(preds_b0==labels_all).mean():<12.2%} {s_b0:<18.4f} {sizes['EfficientNet-B0']:.1f}")
print(f"{'EfficientNet-B2':<20} {(preds_b2==labels_all).mean():<12.2%} {s_b2:<18.4f} {sizes['EfficientNet-B2']:.1f}")
print(f"{'ResNet50':<20} {(preds_resnet==labels_all).mean():<12.2%} {s_resnet:<18.4f} {sizes['ResNet50']:.1f}")

"""### Confusion Matrix — 20 Worst Classes (ResNet50)"""

from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(labels_all, preds_resnet)
per_class_acc = cm.diagonal() / cm.sum(axis=1)
worst_idx = np.argsort(per_class_acc)[:20]
worst_names = [class_names[i] for i in worst_idx]

cm_worst = cm[np.ix_(worst_idx, worst_idx)]
fig, ax = plt.subplots(figsize=(14, 12))
sns.heatmap(cm_worst, annot=True, fmt='d', cmap='Blues',
            xticklabels=worst_names, yticklabels=worst_names, ax=ax)
ax.set_title('Confusion Matrix — 20 Worst Classes (ResNet50)', fontsize=14)
ax.set_xlabel('Predicted')
ax.set_ylabel('Actual')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

print('\nTop 20 worst classes:')
for i, idx in enumerate(worst_idx):
    print(f'{i+1:2d}. {class_names[idx]:<25s} Accuracy: {per_class_acc[idx]:.2%}')

"""###  Most Confused Class Pairs

"""

cm_copy = cm.copy()
np.fill_diagonal(cm_copy, 0)

print('Top 15 Most Confused Class Pairs:')
print(f'{"Actual":<25s} {"Predicted As":<25s} {"Count"}')
print('=' * 60)
for _ in range(15):
    i, j = np.unravel_index(cm_copy.argmax(), cm_copy.shape)
    print(f'{class_names[i]:<25s} {class_names[j]:<25s} {int(cm_copy[i, j])}')
    cm_copy[i, j] = 0

"""### Most Wrong Predictions (High Confidence Errors)"""

wrong_mask = preds_resnet != labels_all
wrong_idx = np.where(wrong_mask)[0]
wrong_conf = probs_resnet[wrong_idx, preds_resnet[wrong_idx]]
top_wrong = wrong_idx[np.argsort(wrong_conf)[::-1][:9]]

original_test = torchvision.datasets.Food101(root=image_path, split='test', download=False)

fig, axes = plt.subplots(3, 3, figsize=(15, 15))
for i, idx in enumerate(top_wrong):
    ax = axes[i // 3, i % 3]
    img, _ = original_test[idx]
    ax.imshow(img)
    true_lab = class_names[labels_all[idx]]
    pred_lab = class_names[preds_resnet[idx]]
    conf = probs_resnet[idx, preds_resnet[idx]]
    ax.set_title(f'True: {true_lab}\nPred: {pred_lab}\nConf: {conf:.1%}', color='red', fontsize=10)
    ax.axis('off')
plt.suptitle('Most Wrong Predictions — ResNet50', fontsize=14)
plt.tight_layout()
plt.show()

"""### Best vs Worst Classes

"""

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

best_idx = np.argsort(per_class_acc)[-10:]
ax1.barh([class_names[i] for i in best_idx], per_class_acc[best_idx], color='green', alpha=0.7)
ax1.set_xlim(0, 1)
ax1.set_title('Top 10 Best Classes (ResNet50)')
ax1.set_xlabel('Accuracy')

worst_10 = np.argsort(per_class_acc)[:10]
ax2.barh([class_names[i] for i in worst_10], per_class_acc[worst_10], color='red', alpha=0.7)
ax2.set_xlim(0, 1)
ax2.set_title('Top 10 Worst Classes (ResNet50)')
ax2.set_xlabel('Accuracy')

plt.tight_layout()
plt.show()

import gradio as gr

model_resnet.eval()

def predict(image):
    # 1
    img_tensor = test_transform(image).unsqueeze(0).to(device)

    # 2
    with torch.no_grad():
        outputs = model_resnet(img_tensor)

    # 3 probabilities
    probs = torch.softmax(outputs, dim=1)[0]

    # 4
    return {class_names[i]: float(probs[i]) for i in range(len(class_names))}

demo = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="pil"),
    outputs=gr.Label(num_top_classes=5),
    title="FoodVision — Food Image Classifier",
    description="Upload a food image and the model will classify it into one of 101 categories."
)
demo.launch()

